version: '3.8'
services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
       - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_USER=test
      - MONGO_INITDB_PASSWORD=test